### ISSUE TITLE
Flutter submodule matching failed

### ISSUE THREAD

**Issue by WillisLing** [passsy/flutter_wrapper#9]
Due to bad networking, flutter submodule initialized failed.
Then check submodule status, show message below.
```bash
8661d8aecd626f7f57ccbcb735553edc05a2e713 .flutter ((null))
```
In this case, .flutter submodule matching failed.

**Comment by passsy** [comment]
are you using the latest (`1.0.3`) version? 

- `install.sh` matches [`\ \.flutter`](https://github.com/passsy/flutter_wrapper/blob/28e8c00432843917e92e6f9d605a9f232306b094/install.sh#L61) to check the submodule. It works for your case.

- `flutterw` matches [`\ \.flutter$`](https://github.com/passsy/flutter_wrapper/blob/28e8c00432843917e92e6f9d605a9f232306b094/flutterw#L47) for cases the submodule is not pulled yet (indicated with a leading `-`). It does not match your case because your submodule is pulled. Therefore everything is fine.

Can you tell me more about the submodule status? What does `((null))` mean? Where is `HEAD`. It seems like the submodule is fine, only the tags haven't been fetched and `git describe` fails.

And what does not work if the submodule is in such a case? How did you notice something is wrong? What would be a fix?
